id: A46A21002
title: 'The Great Treasure of a Hundred Blessings: A Prayer for the Long Life of Ḍākinī
  Muntso Rinpoche'
type: translation
pechas:
- I4E5105C1
- IF26962F0
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:53:35.121416
  last_modified_at: 2023-01-04 11:53:35.121428
  collections:
  - Fourteenth Dalai Lama Series
  - Works of Tibetan Masters
alignment_to_base:
  I4E5105C1/FAED: 5F00
  IF26962F0/6444: 5F00
